"""empty message

Revision ID: 6ab0c1110a9f
Revises: dc87c5a90d0f
Create Date: 2023-09-28 19:13:03.561779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab0c1110a9f'
down_revision = 'dc87c5a90d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captions')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('caption')

    op.create_table('captions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('imageId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['imageId'], ['images.id'], name='fk_captions_imageId_images'),
    sa.PrimaryKeyConstraint('id', name='captions_pkey')
    )
    # ### end Alembic commands ###
