"""initial revision

Revision ID: dc87c5a90d0f
Revises: 
Create Date: 2023-09-27 11:44:23.683285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc87c5a90d0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('originals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('simplifiedText', sa.Boolean(), nullable=True),
    sa.Column('addCaptions', sa.Boolean(), nullable=True),
    sa.Column('addImages', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('modifiedResources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('originalId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['originalId'], ['originals.id'], name=op.f('fk_modifiedResources_originalId_originals')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('fk_modifiedResources_userId_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modifiedId', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modifiedId'], ['modifiedResources.id'], name=op.f('fk_images_modifiedId_modifiedResources')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modifiedId', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modifiedId'], ['modifiedResources.id'], name=op.f('fk_text_modifiedId_modifiedResources')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('captions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageId', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['imageId'], ['images.id'], name=op.f('fk_captions_imageId_images')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captions')
    op.drop_table('text')
    op.drop_table('images')
    op.drop_table('modifiedResources')
    op.drop_table('users')
    op.drop_table('originals')
    # ### end Alembic commands ###
